<?php

/**
 * @file
 * Contains migrate_creporter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_creporter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_creporter module.
    case 'help.page.migrate_creporter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate Community Reporter Site') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function migrate_creporter_media_presave(Drupal\media_entity\MediaInterface $media) {
  if ($media->bundle() == 'MY_BUNDLE_NAME' && !$media->isNew()) {
    $media->automaticallySetThumbnail();
  }
}
// hook_migrate_MIGRATION_ID_prepare_row() is also available.
// //function migrate_munros_migrate_prepare_row(Row $row,
// MigrateSourceInterface $source, MigrationInterface $migration) {
function migrate_creporter_migrate_prepare_row($row, $source, $migration) {
}
function migrate_creporter_migrate_creporter_media_embedded_prepare_row($row, $source, $migration) {
 $video = $row->getSourceProperty('field_video');
 if(!$video) {
    return false;
 } 
}
function migrate_creporter_migrate_creporter_content_stories_prepare_row($row, $source, $migration) {
 $description = $row->getSourceProperty('field_description');
 $description['value'] = $description[0]['value'];
 $row->setSourceProperty('field_description', $description);

}
